name: test

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - perl:5.42
          - perl:5.40
          - perl:5.38
          - perl:5.36
          - perl:5.34
          - perl:5.32
          - perl:5.30
          - perl:5.28
          - perl:5.26
          - perl:5.24-buster
          - perl:5.22-buster
          - perl:5.20-buster
          - perl:5.18-buster
          - perl:5.16-buster
          - perl:5.14-buster
          - perl:5.12-buster
    name: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - run: cpanm -nq LWP::Protocol::https
      - run: cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .
      - run: PERL_USE_UNSAFE_INC=1 prove -v -lr xt -j9
